/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.leetcode;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

public class App {
    public static int lengthOfLongestSubstring(String s) {
        Set<Character> set = new HashSet<>();
        int i = 0;
        int max = 0;

        for (int j = 0; j < s.length(); ++j) {
            if (set.contains(s.charAt(j))) {
                while (s.charAt(i) != s.charAt(j)) {
                    set.remove(s.charAt(i));
                    ++i;
                }
                set.remove(s.charAt(i));
                ++i;
            }
            set.add(s.charAt(j));
            max = Math.max(max, j - i + 1);
        }
        return max;
    }

    public static void main(String[] args) {
        System.out.println(lengthOfLongestSubstring("dvdf"));
    }

    public int[] twoSum(int[] nums, int target) {
        Map<Integer, Integer> map = new HashMap<>();

        for (int i = 0; i < nums.length; ++i) {
            if (map.containsKey(target - nums[i]))
                return new int[]{map.get(target - nums[i]), i};
            map.put(nums[i], i);
        }
        return null;
    }
}
