/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.leetcode.string;

import java.util.HashSet;
import java.util.Set;

public class _3_LongestSubstringWithoutRepeatingCharacters {
    public static int lengthOfLongestSubstring(String s) {
        Set<Character> set = new HashSet<>();
        int i = 0;
        int max = 0;

        for (int j = 0; j < s.length(); ++j) {
            if (set.contains(s.charAt(j))) {
                while (s.charAt(i) != s.charAt(j)) {
                    set.remove(s.charAt(i));
                    ++i;
                }
                set.remove(s.charAt(i));
                ++i;
            }
            set.add(s.charAt(j));
            max = Math.max(max, j - i + 1);
        }
        return max;
    }

    public static void main(String[] args) {
        System.out.println(lengthOfLongestSubstring("dvdf"));
    }


}
