/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.leetcode.string;

import java.util.HashSet;
import java.util.Set;

public class _M_3_LongestSubstringWithoutRepeatingCharacters {
    public static int lengthOfLongestSubstring(String s) {
        int lo = 0, hi = 0;
        int max = 0;

        Set<Character> charSet = new HashSet<>();
        while (hi < s.length()) {
            if (!charSet.contains(s.charAt(hi))) {
                charSet.add(s.charAt(hi));
                max = Math.max(max, hi - lo + 1);
            } else {
                while (lo <= hi && charSet.contains(s.charAt(hi))) {
                    charSet.remove(s.charAt(lo));
                    lo++;
                }
                charSet.add(s.charAt(hi));
            }
            hi++;
        }
        return max;
    }

    public static void main(String[] args) {
        System.out.println(lengthOfLongestSubstring("dvdf"));
    }


}
