/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode.string;

import java.util.HashSet;
import java.util.Set;

public class M_3_LongestSubstringWithoutRepeatingCharacters {
    public static int lengthOfLongestSubstring(String s) {
        int lo = 0, hi = 0;
        int max = Integer.MIN_VALUE;

        Set<Character> set = new HashSet<>();
        while (hi < s.length()) {
            if (!set.contains(s.charAt(hi))) {
                set.add(s.charAt(hi));
                max = Math.max(max, hi - lo + 1);
            } else {
                while (lo <= hi && set.contains(s.charAt(hi))) {
                    set.remove(s.charAt(lo));
                    lo++;
                }
                set.add(s.charAt(hi));
            }
            hi++;
        }
        return max;
    }

    public static void main(String[] args) {
        System.out.println(lengthOfLongestSubstring("bbbb"));
    }


}
