/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode.array.slidingwindow;

public class M_3_LongestSubstringWithoutRepeatingCharacters {

    /**
     * Sliding Window
     */
    public static int lengthOfLongestSubstring(String s) {
        int res = 0;
        int[] frequencies = new int[128];
        int l = 0;

        for (int r = 0; r < s.length(); ++r) {
            frequencies[s.charAt(r)]++;

            while (frequencies[s.charAt(r)] > 1) {
                frequencies[s.charAt(l)]--;
                l++;
            }

            res = Math.max(res, r - l + 1);
        }

        return res;
    }

    static void main() {
        System.out.println(lengthOfLongestSubstring("bbbb"));
    }
}
