/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode.array.slidingwindow;

public class M_3_LongestSubstringWithoutRepeatingCharacters {

    /**
     * Sliding Window
     */
    public static int lengthOfLongestSubstring(String s) {
        int res = 0;
        int n = s.length();
        int[] freq = new int[128];
        int l = 0;

        for (int r = 0; r < n; ++r) {
            char rChar = s.charAt(r);
            freq[rChar]++;

            while (l <= r && freq[rChar] > 1) {
                freq[s.charAt(l)]--;
                l++;
            }

            res = Math.max(res, r - l + 1);
        }

        return res;
    }

    public static void main(String[] args) {
        System.out.println(lengthOfLongestSubstring("bbbb"));
    }
}
